# Generated by Django 4.0.6 on 2022-07-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.CharField(max_length=10, null=True)),
                ('bookName', models.CharField(max_length=50, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('publishedDate', models.DateField(null=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
