# Generated by Django 4.0.6 on 2022-07-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Crime', 'Crime'), ('Mystery', 'Mystery'), ('Rom-Com', 'Rom-Com'), ('Sci-fy', 'Sci-fy')], max_length=20, null=True),
        ),
    ]
