# Generated by Django 4.0.6 on 2022-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='books'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Crime', 'Crime'), ('Mystery', 'Mystery'), ('Rom-Com', 'Rom-Com'), ('Sci-fy', 'Sci-fy'), ('Action', 'Action'), ('Thriller', 'Thriller')], max_length=20, null=True),
        ),
    ]
