# Generated by Django 4.0.6 on 2022-07-29 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_alter_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserveDate', models.DateField(auto_now_add=True)),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
