# Generated by Django 4.0.6 on 2022-07-30 06:38

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_reservebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservebook',
            name='expireDate',
            field=models.DateField(default=dashboard.models.expire),
        ),
    ]
