# Generated by Django 4.0.6 on 2022-07-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_bookid_reservebook_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.book', unique=True),
        ),
    ]
