# Generated by Django 4.0.6 on 2022-07-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_reservebook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservebook',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
