# Generated by Django 4.0.6 on 2022-07-31 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_reservebook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.book'),
        ),
    ]
